apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: payments
  labels:
    app: payment-gateway
spec:
  # NodePort makes it reachable from outside the cluster (for local dev)
  # In production this would be a LoadBalancer fronted by an API gateway / WAF
  type: NodePort
  selector:
    app: payment-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
